-- Schema updates for Complete model --

-- v1 (0.9.4) --

ALTER TABLE  CPT_COMPLETION ADD INDEX (EDU_COURSE);
ALTER TABLE  CPT_COMPLETION ADD INDEX (STUDENT_ID);

CREATE TABLE IF NOT EXISTS CPT_PED_DECISION (
  P_ID smallint NOT NULL,
  STUDENT_ID int NOT NULL,
  SPEC_DECISION varchar(255),
  DECISION_FLAGS tinyint NOT NULL,
  PRIMARY KEY (P_ID),
  UNIQUE INDEX (STUDENT_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('Complete',1,'0.9.4');