CREATE DATABASE 'RujelStatic' DEFAULT CHARACTER SET utf8;

CREATE TABLE BASE_BY_COURSE (
  SC_ID int NOT NULL,
  SETTING_ID int NOT NULL,
  EDU_YEAR smallint,
  EDU_COURSE smallint,
  EDU_CYCLE int,
  GRADE_NUM smallint,
  EDU_GROUP int,
  TEACHER_ID int,
  TEXT_VALUE varchar(255),
  NUM_VALUE int,
  PRIMARY KEY (SC_ID)
);

CREATE TABLE BASE_COURSE (
  CR_ID smallint NOT NULL,
  EDU_CYCLE smallint NOT NULL,
  EDU_GROUP int NOT NULL,
  TEACHER_ID int,
  EDU_YEAR smallint NOT NULL,
  COMMENT_TEXT varchar(255),
  CR_FLAGS smallint NOT NULL,
  PRIMARY KEY (CR_ID)
);

CREATE TABLE BASE_EDU_CYCLE (
  C_ID smallint NOT NULL,
  GRADE_NUM smallint,
  SUBJECT_NAME varchar(28),
  SUB_GROUPS smallint NOT NULL,
  PRIMARY KEY (C_ID)
);

CREATE TABLE BASE_ENTITYS (
  E_ID smallint NOT NULL,
  ENTITY_NAME varchar(28) NOT NULL,
  SQL_TABLE varchar(255),
  PRIMARY KEY (E_ID)
);

CREATE TABLE BASE_SETTINGS (
  S_ID int NOT NULL,
  SETTING_KEY varchar(28) NOT NULL,
  TEXT_VALUE varchar(255),
  NUM_VALUE int,
  PRIMARY KEY (S_ID)
);

CREATE TABLE CR_BORDER (
  B_ID smallint NOT NULL,
  B_SET smallint NOT NULL,
  LEAST_VALUE decimal(4,2) NOT NULL,
  B_TITLE varchar(28) NOT NULL,
  PRIMARY KEY (B_ID)
);

CREATE TABLE CR_BORDER_SET (
  BS_ID smallint NOT NULL,
  BSET_NAME varchar(28),
  ZERO_VALUE varchar(28),
  EXCLUDE_MIN smallint NOT NULL,
  FORMAT_STRING varchar(255),
  USE_CLASS varchar(255),
  PRIMARY KEY (BS_ID)
);

CREATE TABLE CR_CRITERION (
  CRIT_SET smallint NOT NULL,
  CRITER_NUM smallint NOT NULL,
  CR_TITLE varchar(5),
  COMMENT_TEXT varchar(255),
  DFLT_MAX smallint,
  DFLT_WEIGHT smallint,
  INDEX_ID smallint,
  PRIMARY KEY (CRIT_SET,CRITER_NUM)
);

CREATE TABLE CR_CRIT_SET (
  CS_ID smallint NOT NULL,
  COMMENT_TEXT varchar(255),
  SET_NAME varchar(28),
  PRIMARY KEY (CS_ID)
);

CREATE TABLE CR_INDEXER (
  IND_ID smallint NOT NULL,
  INDEX_NAME varchar(28),
  INDEX_TYPE smallint NOT NULL,
  DEFAULT_VALUE varchar(255),
  PRIMARY KEY (IND_ID)
);

CREATE TABLE CR_INDEX_ROW (
  ROW_IDX smallint NOT NULL,
  INDEX_ID smallint NOT NULL,
  IDX_VALUE varchar(255),
  PRIMARY KEY (INDEX_ID,ROW_IDX)
);

CREATE TABLE ITOG_COMMENT (
  ITOG_CONTAINER smallint NOT NULL,
  EDU_CYCLE int NOT NULL,
  STUDENT_ID int NOT NULL,
  COMMENT_TEXT BLOB SUB_TYPE TEXT NOT NULL,
  PRIMARY KEY (ITOG_CONTAINER,EDU_CYCLE,STUDENT_ID)
);

CREATE TABLE ITOG_CONTAINER (
  I_ID smallint NOT NULL,
  ITOG_TYPE smallint NOT NULL,
  ORDER_NUM smallint,
  EDU_YEAR smallint NOT NULL,
  PRIMARY KEY (I_ID)
);

CREATE TABLE ITOG_MARK (
  ITOG_CONTAINER smallint NOT NULL,
  EDU_CYCLE int NOT NULL,
  STUDENT_ID int NOT NULL,
  MARK_TITLE varchar(5) NOT NULL,
  SUCCESS_VALUE decimal(5,4),
  ITOG_FLAGS smallint NOT NULL,
  PRIMARY KEY (ITOG_CONTAINER,EDU_CYCLE,STUDENT_ID)
);

CREATE TABLE ITOG_TYPE (
  T_ID smallint NOT NULL,
  SHORT_TITLE varchar(5),
  TYPE_NAME varchar(28),
  IN_YEAR_COUNT smallint NOT NULL,
  SORT_NUM smallint NOT NULL,
  PRIMARY KEY (T_ID)
);

CREATE TABLE ITOG_TYPE_LIST (
  TL_ID int NOT NULL,
  LIST_NAME varchar(28) NOT NULL,
  ITOG_TYPE smallint NOT NULL,
  PRIMARY KEY (TL_ID)
);

CREATE TABLE PL_CYCLE (
  C_ID smallint NOT NULL,
  GRADE_NUM smallint NOT NULL,
  SPEC_CLASS int,
  SUBJECT_ID smallint NOT NULL,
  TOTAL_HOURS smallint NOT NULL,
  LEVEL_EDU smallint NOT NULL,
  SCHOOL_NUM smallint NOT NULL,
  EDU_YEAR smallint NOT NULL,
  PRIMARY KEY (C_ID)
);

CREATE TABLE PL_HOLIDAY_TYPE (
  HT_ID smallint NOT NULL,
  HOLIDAY_NAME varchar(28) NOT NULL,
  BEGIN_MONTH smallint NOT NULL,
  BEGIN_DAY smallint NOT NULL,
  END_MONTH smallint NOT NULL,
  END_DAY smallint NOT NULL,
  PRIMARY KEY (HT_ID)
);

CREATE TABLE PL_SUBJECT (
  S_ID smallint NOT NULL,
  AREA_ID smallint NOT NULL,
  SORT_NUM smallint NOT NULL,
  SHORT_NAME varchar(28) NOT NULL,
  FULL_NAME varchar(255),
  SUB_GROUPS smallint NOT NULL,
  NORMAL_GROUP smallint NOT NULL,
  PRIMARY KEY (S_ID)
);

CREATE TABLE PL_SUBJ_AREA (
  A_ID smallint NOT NULL,
  AREA_NAME varchar(28) NOT NULL,
  SORT_NUM smallint NOT NULL,
  PRIMARY KEY (A_ID)
);

