USE Contacts;

ALTER TABLE `CONTACT` RENAME TO `CNT_CONTACT`,
 CHANGE COLUMN `CONTACT` `CONTACT_STRING` VARCHAR(255),
 CHANGE COLUMN `FLAGS` `CNT_FLAGS` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `KIND` `KIND_DESRIPT` VARCHAR(28),
 CHANGE COLUMN `PERSON` `PERSON_ID` INTEGER NOT NULL,
 CHANGE COLUMN `TYPE` `CNT_TYPE` SMALLINT(6) NOT NULL;

ALTER TABLE `contype` RENAME TO `CNT_TYPE`,
 CHANGE COLUMN `TYPE` `TYPE_NAME` VARCHAR(28),
 CHANGE COLUMN `UTILISER` `UTILISER_CLASS` VARCHAR(255);
