ALTER TABLE `MARK_ARCHIVE` RENAME TO `MA_MARK_ARCHIVE`,
 CHANGE COLUMN `ID` `A_ID` INTEGER NOT NULL,
 CHANGE COLUMN `DATA` `ARCH_DATA` TEXT NOT NULL,
 CHANGE COLUMN `ENTITY` `OBJ_ENTITY` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `KEY1` `KEY1_VALUE` INTEGER NOT NULL,
 CHANGE COLUMN `KEY2` `KEY2_VALUE` INTEGER NOT NULL,
 CHANGE COLUMN `KEY3` `KEY3_VALUE` INTEGER NOT NULL,
 CHANGE COLUMN `STAMP` `CHANGE_TIME` TIMESTAMP NOT NULL,
 CHANGE COLUMN `USER` `BY_USER` VARCHAR(255) NOT NULL,
 CHANGE COLUMN `WOSID` `WOSID_CODE` VARCHAR(28) NOT NULL;

ALTER TABLE `USED_ENTITY` RENAME TO `MA_USED_ENTITY`,
 CHANGE COLUMN `KEY1` `KEY1_NAME` VARCHAR(28),
 CHANGE COLUMN `KEY2` `KEY2_NAME` VARCHAR(28),
 CHANGE COLUMN `KEY3` `KEY3_NAME` VARCHAR(28),
 CHANGE COLUMN `TOARCHIVE` `TO_ARCHIVE` VARCHAR(28);

ALTER TABLE `AUTOITOG` RENAME TO `AI_AUTOITOG`,
 CHANGE COLUMN `FLAGS` `AI_FLAGS` TINYINT(4) NOT NULL;

ALTER TABLE `BONUS` RENAME TO `AI_BONUS`,
 CHANGE COLUMN `VALUE` `ADD_VALUE` DECIMAL(4,4) NOT NULL,
 CHANGE COLUMN `MARK` `TARGET_MARK` VARCHAR(5),
 CHANGE COLUMN `REASON` `BONUS_REASON` VARCHAR(255);

ALTER TABLE `COURSE_TIMEOUT` RENAME TO `AI_COURSE_TIMEOUT`,
 CHANGE COLUMN `ITOG` `ITOG_CONTAINER` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `COURSE` `EDU_COURSE` INTEGER,
 CHANGE COLUMN `CYCLE` `EDU_CYCLE` MEDIUMINT(9),
 CHANGE COLUMN `TEACHER` `TEACHER_ID` INTEGER,
 CHANGE COLUMN `REASON` `REASON_TEXT` VARCHAR(255),
 CHANGE COLUMN `FLAGS` `CTO_FLAGS` TINYINT(4) NOT NULL;

ALTER TABLE `ITOG_RELATED` RENAME TO `AI_ITOG_RELATED`,
 CHANGE COLUMN `COURSE` `EDU_COURSE` INTEGER NOT NULL,
 CHANGE COLUMN `ITOG` `ITOG_CONTAINER` SMALLINT(6) NOT NULL;

ALTER TABLE `PROGNOSIS` RENAME TO `AI_PROGNOSIS`,
 CHANGE COLUMN `ITOG` `ITOG_CONTAINER` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `COURSE` `EDU_COURSE` INTEGER NOT NULL,
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL,
 CHANGE COLUMN `MARK` `PR_MARK` VARCHAR(5),
 CHANGE COLUMN `VALUE` `SUCCESS_VALUE` DECIMAL(5,4) NOT NULL,
 CHANGE COLUMN `COMPLETE` `COMPLETE_RATE` DECIMAL(5,4) NOT NULL,
 CHANGE COLUMN `BONUS` `BONUS_ID` MEDIUMINT(9),
 CHANGE COLUMN `FLAGS` `PR_FLAGS` TINYINT(4) NOT NULL;

ALTER TABLE `STUDENT_TIMEOUT` RENAME TO `AI_STUDENT_TIMEOUT`,
 CHANGE COLUMN `ITOG` `ITOG_CONTAINER` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL,
 CHANGE COLUMN `COURSE` `EDU_COURSE` INTEGER,
 CHANGE COLUMN `REASON` `REASON_TEXT` VARCHAR(255),
 CHANGE COLUMN `FLAGS` `STO_FLAGS` TINYINT(4) NOT NULL;

ALTER TABLE `BASE_LESSON` CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `THEME` `LESSON_THEME` VARCHAR(255),
 CHANGE COLUMN `TITLE` `LESSON_TITLE` VARCHAR(5),
 CHANGE COLUMN `TASK` `HOME_TASK` INTEGER;

ALTER TABLE `BASE_NOTE`
 CHANGE COLUMN `LESSON` `LESSON_ID` INTEGER NOT NULL,
 CHANGE COLUMN `NOTE` `NOTE_TEXT` VARCHAR(255),
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL;

ALTER TABLE `BASE_TAB`
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `FIRST` `FIRST_LESSON` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `ENTITY` `LESSON_ENTITY` SMALLINT(6) NOT NULL;

ALTER TABLE `COURSE_AUDIENCE` RENAME TO `BASE_AUDIENCE`,
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL;

ALTER TABLE `TEXT_STORE` RENAME TO `BASE_TEXT_STORE`,
 CHANGE COLUMN `ENTITY` `FROM_ENTITY` SMALLINT(6) NOT NULL;

CREATE TABLE BASE_TEACHER_CHANGE (
  TC_ID SMALLINT NOT NULL,
  EDU_COURSE SMALLINT NOT NULL,
  UPTO_DATE DATE NOT NULL,
  TEACHER_ID MEDIUMINT,
  COMMENT_TEXT VARCHAR(255),
  PRIMARY KEY (TC_ID)
);

ALTER TABLE `CRITER_MASK` RENAME TO `CR_MASK`,
 CHANGE COLUMN `CRITERION` `CRITER_NUM` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `MAX` `MARK_MAX` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `WEIGHT` `CRITER_WEIGHT` SMALLINT(6),
 CHANGE COLUMN `WORK` `WORK_ID` MEDIUMINT(9) NOT NULL;

ALTER TABLE `MARK` RENAME TO `CR_MARK`,
 CHANGE COLUMN `CRITER` `CRITER_NUM` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL,
 CHANGE COLUMN `VALUE` `MARK_VALUE` SMALLINT(6),
 CHANGE COLUMN `WORK` `WORK_ID` MEDIUMINT(9) NOT NULL;

ALTER TABLE `WORK` RENAME TO `CR_WORK`,
 CHANGE COLUMN `weight` `WORK_WEIGHT` DECIMAL(4,2) NOT NULL,
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `DEADLINE` `DEADLINE_DATE` DATE NOT NULL,
 CHANGE COLUMN `NUMBER` `NUMBER_ORDER` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `THEME` `WORK_THEME` VARCHAR(255),
 CHANGE COLUMN `TITLE` `WORK_TITLE` VARCHAR(5),
 CHANGE COLUMN `ANNOUNCE` `ANNOUNCE_DATE` DATE NOT NULL,
 CHANGE COLUMN `TASK` `TASK_LINK` INTEGER,
 CHANGE COLUMN `TYPE` `WORK_TYPE` SMALLINT(6) NOT NULL
 ADD COLUMN `WORK_FLAGS` SMALLINT NOT NULL;

UPDATE CR_WORK set WORK_FLAGS = 12 where WORK_TYPE = 0;
UPDATE CR_WORK set WORK_FLAGS = 28 where WORK_TYPE = 1;
UPDATE CR_WORK set WORK_FLAGS = 9 where WORK_TYPE = 2;
UPDATE CR_WORK set WORK_FLAGS = 3 where WORK_TYPE = 3;

ALTER TABLE `WORK_NOTE` RENAME TO `CR_NOTE`,
 CHANGE COLUMN `WORK` `WORK_ID` INTEGER NOT NULL,
 CHANGE COLUMN `NOTE` `NOTE_TEXT` VARCHAR(255),
 CHANGE COLUMN `STUDENT` `STUDENT_ID` INTEGER NOT NULL;

ALTER TABLE `REASON` RENAME TO `CU_REASON`,
 CHANGE COLUMN `BEGIN` `DATE_BEGIN` DATE NOT NULL,
 CHANGE COLUMN `END` `DATE_END` DATE,
 CHANGE COLUMN `REASON` `REASON_TEXT` VARCHAR(255) NOT NULL,
 CHANGE COLUMN `TEACHER` `TEACHER_ID` MEDIUMINT(9),
 CHANGE COLUMN `VERIFICATION` `VERIFY_TEXT` VARCHAR(255),
 CHANGE COLUMN `SCHOOL` `SCHOOL_NUM` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `FLAGS` `REASON_FLAGS` TINYINT(4) NOT NULL;

ALTER TABLE `REPRIMAND` RENAME TO `CU_REPRIMAND`,
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `RAISED` `DATE_RAISED` DATETIME NOT NULL,
 CHANGE COLUMN `RELIEF` `DATE_RELIEF` DATETIME,
 CHANGE COLUMN `CONTENT` `CONTENT_TEXT` VARCHAR(255) NOT NULL,
 CHANGE COLUMN `AUTHOR` `AUTHOR_NAME` VARCHAR(255) NOT NULL,
 CHANGE COLUMN `STATUS` `STATUS_FLAG` TINYINT(4) NOT NULL;

ALTER TABLE `SUBSTITUTE` RENAME TO `CU_SUBSTITUTE`,
 CHANGE COLUMN `LESSON` `LESSON_ID` INTEGER NOT NULL,
 CHANGE COLUMN `REASON` `REASON_ID` MEDIUMINT(9) NOT NULL,
 CHANGE COLUMN `TEACHER` `TEACHER_ID` MEDIUMINT(9) NOT NULL,
 CHANGE COLUMN `FACTOR` `SUBS_FACTOR` DECIMAL(4,2) NOT NULL;

ALTER TABLE `VARIATION` RENAME TO `CU_VARIATION`,
 CHANGE COLUMN `V_DATE` `VAR_DATE` DATE NOT NULL,
 CHANGE COLUMN `VALUE` `VAR_VALUE` TINYINT(4) NOT NULL,
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6),
 CHANGE COLUMN `REASON` `REASON_ID` MEDIUMINT(9) NOT NULL;

ALTER TABLE `EDU_PERIOD` RENAME TO `PL_EDU_PERIOD`,
 CHANGE COLUMN `BEGIN` `DATE_BEGIN` DATE NOT NULL,
 CHANGE COLUMN `END` `DATE_END` DATE NOT NULL,
 CHANGE COLUMN `TITLE` `SHORT_TITLE` VARCHAR(9) NOT NULL,
 CHANGE COLUMN `NAME` `FULL_NAME` VARCHAR(28);

ALTER TABLE `HOLIDAY` RENAME TO `PL_HOLIDAY`,
 CHANGE COLUMN `TYPE` `HD_TYPE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `BEGIN` `DATE_BEGIN` DATE NOT NULL,
 CHANGE COLUMN `END` `DATE_END` DATE NOT NULL;

ALTER TABLE `PERIOD_LIST` RENAME TO `PL_PERIOD_LIST`,
 CHANGE COLUMN `PERIOD` `EDU_PERIOD` SMALLINT(6) NOT NULL;

ALTER TABLE `PLAN_DETAIL` RENAME TO `PL_PLAN_DETAIL`,
 CHANGE COLUMN `COURSE` `EDU_COURSE` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `PERIOD` `EDU_PERIOD` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `HOURS` `TOTAL_HOURS` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `WEEKLY` `WEEKLY_HOURS` SMALLINT(6) NOT NULL;

ALTER TABLE `DESCRIPTION` RENAME TO `ST_DESCRIPTION`,
 CHANGE COLUMN `DESCRIPTION` `ST_DESCRIPTION` VARCHAR(28),
 CHANGE COLUMN `GROUPING1` `GR_FIELD1` VARCHAR(28),
 CHANGE COLUMN `GROUPING2` `GR_FIELD2` VARCHAR(28);

ALTER TABLE `GROUPING` RENAME TO `ST_GROUPING`,
 CHANGE COLUMN `DESCRIPTION` `DESCRIPTION_ID` SMALLINT(6) NOT NULL,
 CHANGE COLUMN `GID1` `GR_ID1` INTEGER,
 CHANGE COLUMN `GID2` `GR_ID2` INTEGER,
 CHANGE COLUMN `TOTAL` `GR_TOTAL` MEDIUMINT(9) NOT NULL;

ALTER TABLE `ENTRY` RENAME TO `ST_ENTRY`,
 CHANGE COLUMN `GROUPING` `GROUPING_ID` INTEGER NOT NULL;
