-- Schema updates for RujelUsers model --

-- v1 (0.9) --

ALTER TABLE AUT_GROUP
  ADD COLUMN SECTION_NUM smallint;

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('RujelUsers',1,'0.9');
