CREATE DATABASE RujelUsers DEFAULT CHARACTER SET utf8;

CREATE TABLE AUT_USER (
  U_ID int NOT NULL,
  USER_NAME varchar(28) NOT NULL,
  CREDENTIAL_STRING varchar(255),
  PERSON_ID int,
  PERS_ENTITY smallint,
  PRIMARY KEY (U_ID)
);

CREATE TABLE AUT_GROUP (
  G_ID smallint NOT NULL,
  GROUP_TITLE varchar(28) NOT NULL,
  EXTERNAL_EQUIVALENT varchar(255),
  PRIMARY KEY (G_ID)
);

CREATE TABLE AUT_MEMBER (
  USER_ID int NOT NULL,
  GROUP_ID smallint NOT NULL,
  PRIMARY KEY (USER_ID,GROUP_ID)
);

CREATE TABLE AUT_USER_PROPERTIES (
  P_ID int NOT NULL,
  USER_ID int NOT NULL,
  PROP_KEY varchar(28) NOT NULL,
  PROP_VALUE varchar(255) NOT NULL,
  PRIMARY KEY (P_ID)
);

CREATE TABLE  EO_PK_TABLE (
  NAME char(40),
  PK int
);
