-- 2010-05-10 for Firebird
-- execute on every RujelYear database

CREATE TABLE CPT_COMPLETION (
  C_ID integer NOT NULL,
  CPT_ASPECT VARCHAR(28) NOT NULL,
  EDU_COURSE SMALLINT,
  STUDENT_ID INTEGER,
  CLOSE_DATE timestamp,
  WHO_CLOSED VARCHAR(255),
  PRIMARY KEY (C_ID)
);