-- 2010-05-10 for MySQL

USE RujelYear2008;

CREATE TABLE CPT_COMPLETION (
  C_ID INTEGER NOT NULL,
  CPT_ASPECT VARCHAR(28) NOT NULL,
  EDU_COURSE SMALLINT,
  STUDENT_ID INTEGER,
  CLOSE_DATE DATETIME,
  WHO_CLOSED VARCHAR(255),
  PRIMARY KEY (C_ID)
) ENGINE=InnoDB;

USE RujelYear2009;

CREATE TABLE CPT_COMPLETION (
  C_ID INTEGER NOT NULL,
  CPT_ASPECT VARCHAR(28) NOT NULL,
  EDU_COURSE SMALLINT,
  STUDENT_ID INTEGER,
  CLOSE_DATE DATETIME,
  WHO_CLOSED VARCHAR(255),
  PRIMARY KEY (C_ID)
) ENGINE=InnoDB;

USE RujelYear2010;

CREATE TABLE CPT_COMPLETION (
  C_ID INTEGER NOT NULL,
  CPT_ASPECT VARCHAR(28) NOT NULL,
  EDU_COURSE SMALLINT,
  STUDENT_ID INTEGER,
  CLOSE_DATE DATETIME,
  WHO_CLOSED VARCHAR(255),
  PRIMARY KEY (C_ID)
) ENGINE=InnoDB;