USE `RujelYear2011`;

INSERT INTO CR_CRITERION (CRIT_SET,CRITER_NUM,CRITER_FLAGS)
  SELECT CS_ID,0,0 FROM CR_CRIT_SET
    WHERE CRITER_FLAGS < 8
  ON DUPLICATE KEY UPDATE DFLT_MAX = DFLT_MAX;

UPDATE CR_CRIT_SET
  SET CRITER_FLAGS = (CRITER_FLAGS -8)
  WHERE CRITER_FLAGS >= 8;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES VALUES ('Criterial',2,'0.9.5');

ALTER TABLE PL_EDU_PERIOD
  ADD COLUMN `ITOG_ID` smallint;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('EduPlanYearly',3,'0.9.5');

USE `RujelYear2012`;

INSERT INTO CR_CRITERION (CRIT_SET,CRITER_NUM,CRITER_FLAGS)
  SELECT CS_ID,0,0 FROM CR_CRIT_SET
    WHERE CRITER_FLAGS < 8
  ON DUPLICATE KEY UPDATE DFLT_MAX = DFLT_MAX;

UPDATE CR_CRIT_SET
  SET CRITER_FLAGS = (CRITER_FLAGS -8)
  WHERE CRITER_FLAGS >= 8;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES VALUES ('Criterial',2,'0.9.5');

ALTER TABLE PL_EDU_PERIOD
  ADD COLUMN `ITOG_ID` smallint;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('EduPlanYearly',3,'0.9.5');

USE `RujelStatic`;

ALTER TABLE ITOG_TYPE_LIST
  ADD COLUMN `MARK_INDEX` smallint;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('EduResults',2,'0.9.5');

USE `RujelSync`;

CREATE TABLE IF NOT EXISTS SYNC_EVENT (
  E_ID integer NOT NULL,
  SYSTEM_ID smallint NOT NULL,
  BASE_ID smallint,
  EXEC_TIME DATETIME NOT NULL,
  SYNC_ENTITY varchar(28),
  EVENT_RESULT smallint NOT NULL,
  PRIMARY KEY (E_ID),
  INDEX (SYSTEM_ID, BASE_ID)
) ENGINE=InnoDB;

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('RujelSync',2,'0.9.5');