USE RujelYear2012;

ALTER TABLE AI_PROGNOSIS ADD INDEX (FIRE_DATE);
ALTER TABLE AI_PROGNOSIS ADD INDEX (STUDENT_ID);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('AutoItog',2,'0.9.7');


ALTER TABLE BASE_LESSON ADD INDEX (DATE_PERFORMED);
ALTER TABLE BASE_AUDIENCE ADD INDEX (STUDENT_ID);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('BaseYearly',3,'0.9.7');


ALTER TABLE CR_NOTE ADD INDEX (STUDENT_ID);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('Criterial',3,'0.9.7');


ALTER TABLE MA_MARK_ARCHIVE ADD INDEX (CHANGE_TIME);
ALTER TABLE MA_MARK_ARCHIVE ADD INDEX (ACTION_TYPE);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('MarkArchive',3,'0.9.7');


USE Contacts;

ALTER TABLE CNT_CONTACT ADD INDEX (PERSON_ID);

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('Contacts',1,'0.9.7'); 
