-- Schema updates for MarkArchive model --

-- v1 (0.9.1) --

ALTER TABLE MA_MARK_ARCHIVE
  ADD COLUMN ACTION_TYPE tinyint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('MarkArchive',1,'0.9.1');
