-- Schema updates for Stats model --

-- v1 (0.9.4) --

ALTER TABLE ST_ENTRY ADD INDEX (GROUPING_ID);
ALTER TABLE ST_GROUPING ADD INDEX (GR_ID1);

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
  MODEL_NAME varchar(255),
  VERSION_NUMBER smallint unsigned NOT NULL,
  VERSION_TITLE varchar(255),
  INSTALL_DATE timestamp
);

INSERT INTO SCHEMA_VERSION (MODEL_NAME,VERSION_NUMBER,VERSION_TITLE)
  VALUES ('Stats',1,'0.9.4');
