-- 2010-09-04 -- MySQL only!

USE RujelStatic;

ALTER TABLE BASE_COURSE
  MODIFY COLUMN CR_ID mediumint NOT NULL;

ALTER TABLE ITOG_COMMENT
  MODIFY COLUMN EDU_CYCLE smallint NOT NULL;

ALTER TABLE ITOG_MARK
  MODIFY COLUMN EDU_CYCLE smallint NOT NULL;

ALTER TABLE RujelStatic.PL_CYCLE
  DROP COLUMN SPEC_CLASS,
  DROP COLUMN TOTAL_HOURS,
  DROP COLUMN EDU_YEAR,
  DROP COLUMN WEEKLY_HOURS;

CREATE TABLE IF NOT EXISTS TPL_PLAN (
  P_ID smallint NOT NULL,
  FOR_CYCLE smallint NOT NULL,
  PLAN_DESCRIPTION varchar(255),
  AUTHOR_TEACHER int,
  PRIMARY KEY (P_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TPL_THEME (
  T_ID mediumint NOT NULL,
  PLAN_ID smallint NOT NULL,
  ORDER_NUM smallint NOT NULL,
  THEME_STRING varchar(255),
  LESSONS_COUNT tinyint NOT NULL,
  PRIMARY KEY (T_ID)
) ENGINE=InnoDB;

DROP TABLE BASE_BY_COURSE;

DROP TABLE BASE_COURSE;

DROP TABLE BASE_INDEXER;

DROP TABLE BASE_INDEX_ROW;

DROP TABLE BASE_SETTINGS;

DROP TABLE CR_BORDER;

DROP TABLE CR_BORDER_SET;

DROP TABLE CR_CRITERION;

DROP TABLE CR_CRIT_SET;

DROP TABLE CR_WORK_TYPE;
