-- 2009-12-10

ALTER TABLE `VseLists`.`VSE_PERSON`
  MODIFY COLUMN `FIRST_NAME` VARCHAR(28);

ALTER TABLE `VseLists`.`VSE_STUDENT`
  MODIFY COLUMN `PERSON_ID` INTEGER;

ALTER TABLE `VseLists`.`VSE_TEACHER`
  MODIFY COLUMN `PERSON_ID` INTEGER;
